Repository algosup/2024-2025-project-4-web-fpga-team-5, pull requests merged in 2025-03, with the labels that each got.

#3 converting bug-report.md to a yml file for better text handling
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/test-template.md
Labels: documentation, enhancement

#4 converting feature and test templates from md to yml
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/test-case.yml
  .github/ISSUE_TEMPLATE/test-template.md
  .github/ISSUE_TEMPLATE/test-template.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#30 README doc to main
  README.md
  documents/manual/userManual.md
  documents/technical/conventions.md
  documents/technical/images/nodeJSLinux.png
  documents/technical/images/nodeJSMacOS.png
  documents/technical/images/nodeJSWindows.png
  documents/technical/technicalSpecifications.md
  images/cnes.png
  images/d3.png
  images/image.png
  images/json.png
  images/nodeJS.jpg
  images/react.jpeg
  images/vite.png
Labels: documentation

#38 Document to Main
  README.md
  documents/functional/functionalSpecifications.md
  documents/technical/APIDocumentation.md
  images/logo.png
  images/mainpage.png
  images/persona1.jpg
  images/persona2.jpg
  images/student1.png
  images/student2.png
  images/teacher1.png
  images/teacher2.png
Labels: documentation

#40 Mistz software patch 1
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/test-case.yml
  .github/ISSUE_TEMPLATE/test-template.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/CI.yml
  README.md
  documents/functional/functionalSpecifications.md
  documents/manual/userManual.md
  documents/technical/APIDocumentation.md
  documents/technical/conventions.md
  documents/technical/images/nodeJSLinux.png
  documents/technical/images/nodeJSMacOS.png
  documents/technical/images/nodeJSWindows.png
  documents/technical/technicalSpecifications.md
  images/cnes.png
  images/d3.png
  images/image.png
  images/json.png
  images/logo.png
  images/mainpage.png
  images/nodeJS.jpg
  images/persona1.jpg
  images/persona2.jpg
  images/react.jpeg
  images/student1.png
  images/student2.png
  images/teacher1.png
  images/teacher2.png
  images/vite.png
Labels: enhancement

#41 Document
  README.md
  documents/qualityAssurance/defectManagementProcess.md
  documents/qualityAssurance/regressionPlan.md
  documents/qualityAssurance/testPlan.md
  documents/technical/APIDocumentation.md
  documents/technical/technicalSpecifications.md
  images/nodeJSLinux.png
  images/nodeJSMacOS.png
  images/nodeJSWindows.png
Labels: documentation, enhancement

#43 Management
  documents/management/managementArtifacts.md
  documents/management/projectCharter.md
  documents/management/weeklyReports/cumulative.md
  documents/management/weeklyReports/weeklyReport1.md
  documents/management/weeklyReports/weeklyReport2.md
  documents/management/weeklyReports/weeklyReport3.md
  documents/management/weeklyReports/weeklyReport4.md
Labels: documentation, enhancement
